[build]
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/service-worker.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[redirects]]
  from = "/"
  to = "/html/index.html"
  status = 200

[[redirects]]
  from = "/account"
  to = "/html/account.html"
  status = 200

[[redirects]]
  from = "/cart"
  to = "/html/cart.html"
  status = 200

[[redirects]]
  from = "/checkout"
  to = "/html/checkout.html"
  status = 200

[[redirects]]
  from = "/help"
  to = "/html/help.html"
  status = 200

[[redirects]]
  from = "/login"
  to = "/html/login.html"
  status = 200

[[redirects]]
  from = "/products"
  to = "/html/products.html"
  status = 200

[[redirects]]
  from = "/signup"
  to = "/html/signup.html"
  status = 200

[[redirects]]
  from = "/product/*"
  to = "/html/product.html"
  status = 200